-- Seed Cebu higher education institutions from the official CHED HEIDA Region VII directory.
-- Source: https://heida.ched.gov.ph/hei-directory/7?selectedProvinceId=35
-- Fetched on 2026-06-02; HEIDA reported 127 Cebu HEIs.

WITH cebu_schools(name) AS (
  VALUES
  ('ACLC College of Mandaue'),
  ('Advanced Institute of Technology'),
  ('AMA Computer College, Inc. - Cebu City Branch'),
  ('Asian College of Technology'),
  ('Asian College of Technology International Education Foundation, Inc. - Pit-Os Campus'),
  ('Asian College of Technology International Educational Foundation'),
  ('Bantayan Southern Institute, Inc.'),
  ('Baptist Theological College, Inc.'),
  ('Benedicto College-Cebu'),
  ('Benedicto College, Inc. - Mandaue City'),
  ('Benthel Asia School of Technology'),
  ('Bradford Christian College'),
  ('Bradford Christian College, Inc.'),
  ('Carcar City College'),
  ('CATS Aero College, Inc.'),
  ('CBD College'),
  ('Cebu Doctors'' University'),
  ('Cebu Doctors'' University College of Medicine'),
  ('Cebu Eastern College, Inc.'),
  ('Cebu Immanuel Bible College, Inc.'),
  ('Cebu Institute of Medicine, Incorporated'),
  ('Cebu Institute of Technology-University'),
  ('Cebu Mary Immaculate College Inc.'),
  ('Cebu Normal University'),
  ('Cebu Normal University - Balamban'),
  ('Cebu Normal University - Medellin'),
  ('Cebu Polytechnic College'),
  ('Cebu Roosevelt Memorial Colleges, Inc.'),
  ('Cebu Sacred Heart College'),
  ('Cebu Sacred Heart College, Inc.'),
  ('Cebu School of Midwifery'),
  ('Cebu Technological University - Carmen Campus'),
  ('Cebu Technological University - Cebu City Mountain Satellite Campus'),
  ('Cebu Technological University - Consolacion'),
  ('Cebu Technological University - Main'),
  ('Cebu Technological University-Argao Campus'),
  ('Cebu Technological University-Barili Campus'),
  ('Cebu Technological University-Daanbantayan Campus'),
  ('Cebu Technological University-Danao City Campus'),
  ('Cebu Technological University-Moalboal Campus'),
  ('Cebu Technological University-San Francisco Campus'),
  ('Cebu Technological University-Tuburan Campus'),
  ('Central Philippine Bible College'),
  ('Central Philippine Nazarene College, Inc.'),
  ('Centre for International Education Global Colleges, Inc.'),
  ('Colegio de San Antonio de Padua, Inc.'),
  ('College of Technological Sciences-Cebu, Inc.'),
  ('Collegium Societatis Angeli Pacis'),
  ('Consolatrix College of Toledo City, Inc.'),
  ('Cordova Public College'),
  ('De La Salle Andres Soriano Memorial College, Inc.'),
  ('Don Bosco Technical College-Cebu, Inc'),
  ('Evangelical Theological College of the Philippines'),
  ('Felipe R. Verallo Memorial Foundation, Inc.'),
  ('Flight Dynamics School of Aeronautics'),
  ('Golden Success College, Inc.'),
  ('Gullas College of Medicine, Inc.'),
  ('Holy Trinity College'),
  ('iACADEMY, Inc.'),
  ('Indiana School of Aeronautics'),
  ('Informatics College Cebu'),
  ('Interface Computer College'),
  ('La Consolacion College-Liloan, Cebu, Inc.'),
  ('Lapu-Lapu City College'),
  ('LapuLapu-Cebu International College Inc.'),
  ('Larmen De Guia Memorial College'),
  ('Lyceum of Cebu'),
  ('Madridejos Community College'),
  ('Mandaue City College'),
  ('Manto Memorial Foundation College'),
  ('Mary Our Help Technical Institute for Women (Cebu), Incorporated'),
  ('Mary''s Children Formation College, Inc.'),
  ('Matias H. Aznar Memorial College of Medicine, Inc.'),
  ('MHAM College Inc.'),
  ('Microsystem International Institute of Technology, Inc.'),
  ('Mount Moriah College, Incorporated'),
  ('National Aviation Academy of the Philippines'),
  ('Northeastern Cebu Colleges, Inc.'),
  ('Northern Cebu Colleges, Inc.'),
  ('NU Cebu Incorporated'),
  ('Professional Academy of the Philippines, Inc.'),
  ('Rizwoods Colleges - Cebu City Campus'),
  ('Rizwoods Colleges - Liloan Cebu Campus'),
  ('Rizwoods Colleges-Lapu-Lapu City Campus'),
  ('Rizwoods Colleges, Inc.'),
  ('Rogationist Seminary College-Cebu, Inc.'),
  ('Rosemont Hills Montessori College'),
  ('Royal Christian College'),
  ('Saint Louis College -Cebu'),
  ('Saint Paul College Foundation'),
  ('Salazar Colleges of Science and Institute of Technology'),
  ('Salazar Colleges of Science and Institute of Technology-Madridejos'),
  ('Salazar Colleges of Science and Institute of Technology-Talisay City'),
  ('San Carlos Seminary College'),
  ('Seminaryo Mayor de San Carlos'),
  ('Sibonga Community College'),
  ('Southwestern University, Inc.'),
  ('St. Catherine''s College, Inc.'),
  ('St. Cecilia''s College - Cebu, Inc.'),
  ('St. Louise de Marillac College of Bogo, Cebu Inc.'),
  ('St. Paul College Foundation-Mandaue'),
  ('St. Theresa''s College of Cebu'),
  ('St. Vincent College, Inc.'),
  ('STI EDUCATION SERVICES GROUP, INC - STI COLLEGE CEBU'),
  ('Sto. Niño Mactan College Inc.'),
  ('Sto. Tomas College, Danao City, Inc.'),
  ('Tabor Hills College-OAD, Inc.'),
  ('Talisay City College'),
  ('The Concord Technical Institute, Inc.'),
  ('TRADE-TECH INTERNATIONAL SCIENCE INSTITUTE'),
  ('University of Cebu'),
  ('University of Cebu at Pardo and Talisay, Inc.'),
  ('University of Cebu College of Medicine Foundation, Inc'),
  ('University of Cebu-Banilad'),
  ('University of Cebu-Lapulapu and Mandaue, Inc.'),
  ('University of San Carlos'),
  ('University of San Jose-Recoletos'),
  ('University of San Jose-Recoletos - Balamban Campus'),
  ('University of Southern Philippines Foundation, Inc.'),
  ('University of the Philippines - Cebu'),
  ('University of the Visayas'),
  ('University of the Visayas -Gullas College Danao City Branch'),
  ('University of The Visayas-Dalaguete Campus'),
  ('University of the Visayas-Gullas College Minglanilla Campus'),
  ('University of the Visayas-Mandaue Campus'),
  ('University of the Visayas-Toledo City Campus'),
  ('Velez College Inc.')
)
INSERT INTO schools (name)
SELECT cs.name
FROM cebu_schools cs
WHERE NOT EXISTS (
  SELECT 1
  FROM schools existing
  WHERE lower(existing.name) = lower(cs.name)
);

WITH cebu_school_aliases(school_name, aliases) AS (
  VALUES
  ('ACLC College of Mandaue', ARRAY['aclc', 'aclc mandaue']),
  ('Advanced Institute of Technology', ARRAY['ait']),
  ('AMA Computer College, Inc. - Cebu City Branch', ARRAY['ama cebu', 'ama computer college cebu']),
  ('Asian College of Technology', ARRAY['act', 'act cebu', 'asian college of technology cebu']),
  ('Asian College of Technology International Education Foundation, Inc. - Pit-Os Campus', ARRAY['act pit-os', 'act pitos']),
  ('Asian College of Technology International Educational Foundation', ARRAY['act foundation']),
  ('Benedicto College-Cebu', ARRAY['benedicto college', 'benedicto cebu']),
  ('Benedicto College, Inc. - Mandaue City', ARRAY['benedicto mandaue']),
  ('CATS Aero College, Inc.', ARRAY['cats', 'cats aero']),
  ('Cebu Doctors'' University', ARRAY['cdu', 'cebu doctors university']),
  ('Cebu Doctors'' University College of Medicine', ARRAY['cdu medicine', 'cebu doctors medicine']),
  ('Cebu Institute of Medicine, Incorporated', ARRAY['cim', 'cebu institute of medicine']),
  ('Cebu Institute of Technology-University', ARRAY['cit-u', 'cit', 'cebu institute of technology', 'cebu institute of technology university']),
  ('Cebu Normal University', ARRAY['cnu']),
  ('Cebu Normal University - Balamban', ARRAY['cnu balamban']),
  ('Cebu Normal University - Medellin', ARRAY['cnu medellin']),
  ('Cebu Polytechnic College', ARRAY['cpc']),
  ('Cebu Technological University - Carmen Campus', ARRAY['ctu carmen']),
  ('Cebu Technological University - Cebu City Mountain Satellite Campus', ARRAY['ctu mountain', 'ctu mountain satellite']),
  ('Cebu Technological University - Consolacion', ARRAY['ctu consolacion']),
  ('Cebu Technological University - Main', ARRAY['ctu', 'ctu main', 'cebu tech', 'cebu technological university']),
  ('Cebu Technological University-Argao Campus', ARRAY['ctu argao']),
  ('Cebu Technological University-Barili Campus', ARRAY['ctu barili']),
  ('Cebu Technological University-Daanbantayan Campus', ARRAY['ctu daanbantayan']),
  ('Cebu Technological University-Danao City Campus', ARRAY['ctu danao', 'ctu danao city']),
  ('Cebu Technological University-Moalboal Campus', ARRAY['ctu moalboal']),
  ('Cebu Technological University-San Francisco Campus', ARRAY['ctu san francisco']),
  ('Cebu Technological University-Tuburan Campus', ARRAY['ctu tuburan']),
  ('College of Technological Sciences-Cebu, Inc.', ARRAY['cts', 'cts cebu']),
  ('Don Bosco Technical College-Cebu, Inc', ARRAY['dbtc', 'don bosco cebu']),
  ('Gullas College of Medicine, Inc.', ARRAY['gullas medicine', 'gcm']),
  ('Indiana School of Aeronautics', ARRAY['isa', 'isa cebu']),
  ('Informatics College Cebu', ARRAY['informatics', 'informatics cebu']),
  ('Interface Computer College', ARRAY['interface', 'interface cebu']),
  ('Lapu-Lapu City College', ARRAY['llcc']),
  ('LapuLapu-Cebu International College Inc.', ARRAY['lcic', 'lapulapu cebu international college']),
  ('Matias H. Aznar Memorial College of Medicine, Inc.', ARRAY['matias aznar', 'mham medicine']),
  ('MHAM College Inc.', ARRAY['mham', 'mham college']),
  ('National Aviation Academy of the Philippines', ARRAY['naap']),
  ('NU Cebu Incorporated', ARRAY['nu cebu', 'national university cebu']),
  ('Salazar Colleges of Science and Institute of Technology', ARRAY['scsit', 'salazar college']),
  ('Salazar Colleges of Science and Institute of Technology-Madridejos', ARRAY['scsit madridejos']),
  ('Salazar Colleges of Science and Institute of Technology-Talisay City', ARRAY['scsit talisay']),
  ('San Carlos Seminary College', ARRAY['san carlos seminary']),
  ('Seminaryo Mayor de San Carlos', ARRAY['smdsc']),
  ('Southwestern University, Inc.', ARRAY['swu', 'swu phinma', 'southwestern university']),
  ('St. Theresa''s College of Cebu', ARRAY['stc', 'stc cebu', 'saint theresa cebu']),
  ('STI EDUCATION SERVICES GROUP, INC - STI COLLEGE CEBU', ARRAY['sti', 'sti cebu', 'sti college cebu']),
  ('Talisay City College', ARRAY['tcc', 'tcc cebu']),
  ('University of Cebu', ARRAY['uc', 'uc main', 'university of cebu main']),
  ('University of Cebu at Pardo and Talisay, Inc.', ARRAY['uc pardo', 'uc talisay', 'uc pt']),
  ('University of Cebu College of Medicine Foundation, Inc', ARRAY['uc medicine', 'uc med']),
  ('University of Cebu-Banilad', ARRAY['uc banilad', 'uc-b']),
  ('University of Cebu-Lapulapu and Mandaue, Inc.', ARRAY['uclm', 'uc lm', 'uc lapu-lapu', 'uc mandaue']),
  ('University of San Carlos', ARRAY['usc']),
  ('University of San Jose-Recoletos', ARRAY['usjr']),
  ('University of San Jose-Recoletos - Balamban Campus', ARRAY['usjr balamban']),
  ('University of Southern Philippines Foundation, Inc.', ARRAY['uspf']),
  ('University of the Philippines - Cebu', ARRAY['up cebu', 'upc', 'university of the philippines cebu']),
  ('University of the Visayas', ARRAY['uv', 'uv main', 'university of visayas']),
  ('University of the Visayas -Gullas College Danao City Branch', ARRAY['uv danao', 'uv gullas danao']),
  ('University of The Visayas-Dalaguete Campus', ARRAY['uv dalaguete']),
  ('University of the Visayas-Gullas College Minglanilla Campus', ARRAY['uv minglanilla', 'uv gullas minglanilla']),
  ('University of the Visayas-Mandaue Campus', ARRAY['uv mandaue']),
  ('University of the Visayas-Toledo City Campus', ARRAY['uv toledo']),
  ('Velez College Inc.', ARRAY['velez', 'velez college'])
)
INSERT INTO school_aliases (school_id, alias)
SELECT DISTINCT ON (lower(trim(alias_value.alias)))
  s.id,
  lower(trim(alias_value.alias))
FROM cebu_school_aliases csa
JOIN schools s
  ON lower(s.name) = lower(csa.school_name)
CROSS JOIN LATERAL unnest(csa.aliases) AS alias_value(alias)
WHERE trim(alias_value.alias) <> ''
ORDER BY lower(trim(alias_value.alias)), s.id
ON CONFLICT (alias) DO NOTHING;
